FROM docker.io/ollama/ollama:latest

# Install necessary packages and pip
RUN apt-get update && \
    apt-get install -y curl python3 python3-pip && \
    pip3 install llm-bench

RUN ollama serve > /dev/null 2>&1 & \
    sleep 20 && \
    ollama pull llama3:70b