FROM docker.io/ollama/ollama:latest

# Install necessary packages and pip
RUN apt-get update && \
    apt-get install -y curl python3 python3-pip && \
    pip3 install llm-bench

# Start ollama server and check readiness before pulling models
RUN ollama serve > /dev/null 2>&1 & \
    sleep 20 && \
    ollama pull jmorgan/grok
    
ADD start_benchmark_grok.sh start_benchmark_grok.sh

ENTRYPOINT [ "bash", "./start_benchmark_grok.sh" ] 