# Use the lmdeploy image as the base
FROM docker.io/openmmlab/lmdeploy:v0.5.3-cu12

# Install git and any other necessary dependencies
RUN apt-get update && apt-get install -y git

# Prepare cache and model directories
RUN mkdir -p /root/.cache/huggingface/transformers
RUN chmod -R 777 /root/.cache/huggingface/transformers
RUN mkdir -p /root/snapshots
RUN chmod -R 777 /root/snapshots

# Clone and install your GitHub repo
RUN git clone https://github.com/KeesGeerligs/nos_bench.git /lm-benchmark
WORKDIR /lm-benchmark
RUN pip install -e .

# Copy the bash script into the image
COPY run_benchmark_llm_bench.sh /lm-benchmark/run_benchmark_llm_bench.sh

# Make the script executable
RUN chmod +x run_benchmark_llm_bench.sh

# Set the entrypoint to the bash script
ENTRYPOINT ["/lm-benchmark/run_benchmark_llm_bench.sh"]
